AWSTemplateFormatVersion: 2010-09-09
Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for building Chic image
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation
      Tags:
        - Key: Name
          Value: !Sub chic-security-group-${AWS::StackName}
  BuildInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId
      KeyName: !Ref KeyName
      Tags:
        - Key: Name
          Value: !Sub chic-image-builder-${AWS::StackName}
      BlockDeviceMappings:
        - DeviceName: !Ref RootVolumeDeviceName
          Ebs:
            VolumeSize: !Ref RootVolumeSize
      NetworkInterfaces: 
      - AssociatePublicIpAddress: "true"
        DeviceIndex: 0
        GroupSet:
          - !Ref SecurityGroup
        SubnetId: !Ref SubnetId
Parameters:
  InstanceType:
    Description: The instance type to use to build the image.
    Type: String
  ImageId:
    Description: The AMI to use to build the image.
    Type: String
  KeyName:
    Description: The key name to use to start the instance
    Type: String
    Default: ""
  SSHLocation:
    Description: The IP address range that can be used to SSH to the instance
    Type: String
    Default: 0.0.0.0/0
  RootVolumeDeviceName:
    Description: The device name of the root volume
    Type: String
  RootVolumeSize:
    Description: The size of the root volume in GB
    Type: String
  VpcId:
    Description: The VPC to build in
    Type: String
  SubnetId:
    Description: The subnet to build in
    Type: String
Outputs:
  BuildInstanceId:
    Description: The instance ID of the build instance.
    Value: !Ref BuildInstance
  BuildInstancePublicIp:
    Description: The public IP of the build instance.
    Value: !GetAtt BuildInstance.PublicIp
